name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Run tests
        run: bun test
      # Skip Build until this issue is resolved:
      # Module not found: Can't resolve '@/bitte.dev.json'
      # - name: Build
      #   run: bun build:next